session.save_handler = files
session.save_path = /var/lib/php/sessions
session.gc_probability = 1
session.gc_divisor = 100

upload_max_filesize = 1024M
post_max_size = 1024M
max_execution_time = 600
max_input_time = 600
memory_limit = 512M

date.timezone = Europe/Moscow
