upstream php-upstream {
    server php:9000;
}

server {
    listen 80 deferred reuseport default;
    listen [::]:80 deferred reuseport default;

    server_name _;

    charset utf-8;
    root /var/www/bitrix;
    index index.php index.html;

    access_log /var/log/nginx/bitrix-access.log;
    error_log /var/log/nginx/bitrix-error.log;

    add_header X-Content-Type-Options nosniff;

    client_max_body_size 1024m;

    rewrite ^([^.]*?\/)\/+(.*)$ $1$2 permanent;

    if ($request_uri ~* "^(.*/)index\.php$") {
        return 301 $1;
    }

    location / {
        try_files $uri $uri/ @bitrix;
    }

    location @bitrix {
        fastcgi_pass php-upstream;
        include fastcgi_params;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SCRIPT_FILENAME $document_root/bitrix/urlrewrite.php;
    }

    location = /restore.php {
        include fastcgi_params;
        fastcgi_pass php-upstream;
        fastcgi_send_timeout 21600;
        fastcgi_read_timeout 21600;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        client_body_buffer_size 1024m;
        client_max_body_size 1024m;
    }

    location = /favicon.png { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    location ~ (/\.ht|/\.git|/\.gitignore|\.settings\.php|/composer|/bitrix/backup|/bitrix/updates|/bitrix/modules|/bitrix/php_interface|/bitrix/stack_cache|/bitrix/managed_cache|/bitrix/html_pages/\.|/upload/1c_exchange|local/modules|local/php_interface|/logs/) {
        deny all;
    }

    location ~* ^/bitrix/cache/.+\.(js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|ico|map)$ {
        expires max;
        add_header Cache-Control public;
    }

    location ~* ^/bitrix/cache { deny all; }

    location ~ \.php$ {
        if ($request_uri ~* "^(.*/)index\.php$") {
            return 301 $1;
        }
        include fastcgi_params;
        fastcgi_pass php-upstream;
        fastcgi_send_timeout 21600;
        fastcgi_read_timeout 21600;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    error_page 404 /404.html;
    location /404.html {}
}
